/**
 * Generate TypeScript types from `node-types.json` and `grammar.json`.
 *
 *   npx tsx ../genNodeTypes.ts src/ > nodes.ts
 *
 * Format it afterwards:
 *   npx prettier --write nodes.ts
 */

import { readFileSync } from "fs";
import { join } from "path";

// Check if a file path is provided
if (process.argv.length < 3) {
  console.error(`
		npx tsx dev/genNodeTypes.ts <node-types.json and grammar.json folder>
		npx tsx dev/genNodeTypes.ts node_modules/tree-sitter-scala/src/
	`);
  process.exit(1);
}

// Get the file path from the command line arguments
const FOLDER = process.argv[2];

// NodeInfo is defined in tree-sitter node v0.25
// for now keep a placeholder
type BaseNode = {
  type: string;
  named: boolean;
};
type ChildNode = {
  multiple: boolean;
  required: boolean;
  types: BaseNode[];
};
type SuperTypeNodeInfo = BaseNode & {
  subtypes: BaseNode[];
};
type TypeNodeInfo = BaseNode & {
  fields: { [name: string]: ChildNode };
  children: ChildNode[];
};
type NodeInfo = SuperTypeNodeInfo | TypeNodeInfo;

/**
 * Generate TS file from tree-sitter grammar:
 * 1. Define `Abstract${langName}Node extends SyntaxNode`. All nodes
 *    will inherit it
 * 2. Iterate over node-types.json and generate TS type for each node type
 * 2a. Print hardcoded values
 * 3. Define union `${langName}Node` from all node types.
 */
function main(folder: string) {
  const nodeTypesPath = join(folder, "node-types.json");
  const nodeTypes = JSON.parse(
    readFileSync(nodeTypesPath).toString(),
  ) as NodeInfo[];
  const grammarPath = join(folder, "grammar.json");
  const grammar = JSON.parse(readFileSync(grammarPath).toString());

  const langName = grammar.name[0].toUpperCase() + grammar.name.slice(1);
  console.log(`
	  /* Autogenerated, do not edit by hand. */
    /* eslint-disable max-lines */`);

  const abstractNodeName = `Abstract${langName}Node`;
  const unionNodeName = `${langName}Node`;
  console.log(`
		import type { SyntaxNode, Point } from 'tree-sitter';

		export interface ${abstractNodeName} extends SyntaxNode {
			parent: ${unionNodeName} | null;
			namedChildren: Array<${unionNodeName}>;

			descendantsOfType(types: string | Array<string>, startPosition?: Point, endPosition?: Point): Array<${unionNodeName}>;
		}`);

  /**
	 * Print only named nodes. Each node, either
	 * 1. Has fields - we declare interface with fields
	 * 2. Has subtypes - it's supertype
		  https://tree-sitter.github.io/tree-sitter/using-parsers/6-static-node-types.html?highlight=subtypes#supertype-nodes
	 */
  nodeTypes
    .filter((t) => t.named)
    .forEach((nodeType) => {
      if ("subtypes" in nodeType) {
        console.log(genSupertypeDefinition(nodeType, abstractNodeName));
        return;
      }

      console.log(genTypeDefinition(nodeType, abstractNodeName));
    });

  const overrides = GRAMMAR_OVERRIDES[langName] || {
    footer: "",
    interfaces: [],
  };
  console.log(overrides.footer);

  /**
   * print union type (Gather all named nodetypes, exclude supertypes)
   */
  const interfaceNames = nodeTypes
    .filter((t: NodeInfo) => t.named && !("subtypes" in t))
    .map((t: NodeInfo) => typeToInterfaceName(t.type));
  interfaceNames.push(...overrides.interfaces);
  console.log(`export type ${unionNodeName} = ${interfaceNames.join(" | ")};`);
}

interface GrammarOverride {
  footer: string;
  interfaces: string[];
}

const GRAMMAR_OVERRIDES: Record<string, GrammarOverride> = {
  /**
   * Scala node-types.json lacks description for TypeIdentifierNode.
   * this is a quick fix,
   */
  Scala: {
    footer: `
		export interface TypeIdentifierNode extends AbstractScalaNode {
			type: 'type_identifier';
		}`,
    interfaces: ["TypeIdentifierNode"],
  },
};

function genSupertypeDefinition(
  nodeType: SuperTypeNodeInfo,
  abstractNodeName: string,
) {
  const interfaceName = typeToInterfaceName(nodeType.type);
  const subtypes = nodeType.subtypes
    .filter((s) => s.named)
    .map((s) => typeToInterfaceName(s.type));

  // if there are no named subtypes we can ignore it
  // and replace with Abstract${Lang}Node
  if (subtypes.length === 0) {
    return `export type ${interfaceName} = ${abstractNodeName};`;
  }
  return `
		export type ${interfaceName} = ${subtypes.join(" | ")};`;
}

/**
 *
 * reference - initializeLanguageNodeClasses from
 * https://github.com/tree-sitter/node-tree-sitter/blob/master/index.js#L852
 */
function genTypeDefinition(
  nodeType: TypeNodeInfo,
  abstractNodeName: string,
): string {
  const interfaceName = typeToInterfaceName(nodeType.type);
  let body = "";

  for (const [fieldName, field] of Object.entries(nodeType.fields || {})) {
    const memberName = fieldNameToMemberName(fieldName, field.multiple);
    // if all children are unnamed we place an abstractNodeName as fallback
    const memberType = genFieldType(field) ?? abstractNodeName;
    body =
      body +
      `
			${memberName}: ${memberType};`;
  }
  return `

		export interface ${interfaceName} extends ${abstractNodeName} {
			type: '${nodeType.type}';
			${body}
		}`;
}

function typeToInterfaceName(type: string): string {
  let name = toCamelCase(sanitizeTypeName(type)) + "Node";
  name = name[0].toUpperCase() + name.slice(1);
  if (type[0] === "_") {
    name = "_" + name;
  }

  return name;
}

function fieldNameToMemberName(fieldName: string, multiple: boolean): string {
  return (
    toCamelCase(sanitizeTypeName(fieldName)) + (multiple ? "Nodes" : "Node")
  );
}

function genFieldType(nodeType: ChildNode) {
  const interfaces = nodeType.types
    .filter((t) => t.named)
    .map((t) => typeToInterfaceName(t.type));
  if (interfaces.length === 0) {
    return undefined;
  }
  if (nodeType.multiple) {
    return "(" + interfaces.join(" | ") + ")[]";
  }
  if (nodeType.required) {
    return interfaces.join(" | ");
  } else {
    return interfaces.join(" | ") + "| null";
  }
}

/* Convert all non-alphanumeric characters to hexadecimal */
function sanitizeTypeName(type: string) {
  if (type === "_") return "underscore";
  return type.replace(
    /[^a-zA-Z0-9_]/g,
    (c) => `x${c.charCodeAt(0).toString(16)}`,
  );
}

function toCamelCase(str: string) {
  return str.replace(/_(\w)/g, (_, letter: string) => letter.toUpperCase());
}

main(FOLDER);
