/* Autogenerated, do not edit by hand. */
/* eslint-disable max-lines */

import type { SyntaxNode, Point } from "tree-sitter";

export interface AbstractDartNode extends SyntaxNode {
  parent: DartNode | null;
  namedChildren: Array<DartNode>;

  descendantsOfType(
    types: string | Array<string>,
    startPosition?: Point,
    endPosition?: Point,
  ): Array<DartNode>;
}

export type _DeclarationNode =
  | ClassDeclarationNode
  | EnumDeclarationNode
  | ExtensionDeclarationNode
  | ExtensionTypeDeclarationNode
  | MixinDeclarationNode
  | TypeAliasNode;

export type _InstantiationNode =
  ConstObjectExpressionNode | ConstructorInvocationNode | NewExpressionNode;

export type _LiteralNode =
  | DecimalFloatingPointLiteralNode
  | DecimalIntegerLiteralNode
  | FalseNode
  | HexIntegerLiteralNode
  | ListLiteralNode
  | NullLiteralNode
  | RecordLiteralNode
  | SetOrMapLiteralNode
  | StringLiteralNode
  | SymbolLiteralNode
  | TrueNode;

export type _StatementNode =
  | AssertStatementNode
  | BlockNode
  | BreakStatementNode
  | ContinueStatementNode
  | DoStatementNode
  | EmptyStatementNode
  | ExpressionStatementNode
  | ForStatementNode
  | IfStatementNode
  | LabeledStatementNode
  | LocalFunctionDeclarationNode
  | LocalVariableDeclarationNode
  | RethrowStatementNode
  | ReturnStatementNode
  | SwitchStatementNode
  | TryStatementNode
  | WhileStatementNode
  | YieldEachStatementNode
  | YieldStatementNode;

export interface AdditiveExpressionNode extends AbstractDartNode {
  type: "additive_expression";
}

export interface AnnotationNode extends AbstractDartNode {
  type: "annotation";

  nameNode: IdentifierNode | QualifiedNode;
}

export interface AnnotationArgumentsNode extends AbstractDartNode {
  type: "annotation_arguments";
}

export interface ArgumentsNode extends AbstractDartNode {
  type: "arguments";
}

export interface AssertStatementNode extends AbstractDartNode {
  type: "assert_statement";
}

export interface AssertionNode extends AbstractDartNode {
  type: "assertion";
}

export interface AssignableExpressionNode extends AbstractDartNode {
  type: "assignable_expression";

  indexNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  objectNode:
    | _InstantiationNode
    | _LiteralNode
    | CallExpressionNode
    | ConstructorTearoffNode
    | FunctionExpressionNode
    | IdentifierNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | MemberExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | null;
  propertyNode: IdentifierNode | null;
}

export interface AssignmentExpressionNode extends AbstractDartNode {
  type: "assignment_expression";

  leftNode: AssignableExpressionNode;
  operatorNode: AbstractDartNode;
  rightNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface AwaitExpressionNode extends AbstractDartNode {
  type: "await_expression";
}

export interface BinaryOperatorNode extends AbstractDartNode {
  type: "binary_operator";
}

export interface BitwiseAndExpressionNode extends AbstractDartNode {
  type: "bitwise_and_expression";
}

export interface BitwiseOrExpressionNode extends AbstractDartNode {
  type: "bitwise_or_expression";
}

export interface BitwiseXorExpressionNode extends AbstractDartNode {
  type: "bitwise_xor_expression";
}

export interface BlockNode extends AbstractDartNode {
  type: "block";
}

export interface BreakStatementNode extends AbstractDartNode {
  type: "break_statement";
}

export interface CallExpressionNode extends AbstractDartNode {
  type: "call_expression";

  argumentsNode: ArgumentsNode;
  functionNode:
    | _InstantiationNode
    | _LiteralNode
    | CallExpressionNode
    | ConstructorTearoffNode
    | FunctionExpressionNode
    | IdentifierNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | MemberExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode;
}

export interface CascadeCallExpressionNode extends AbstractDartNode {
  type: "cascade_call_expression";

  argumentsNode: ArgumentsNode;
  functionNode:
    | CascadeCallExpressionNode
    | CascadeIndexExpressionNode
    | CascadeMemberExpressionNode
    | CascadeNullAssertionExpressionNode
    | CascadeNullAwareIndexExpressionNode
    | CascadeNullAwareMemberExpressionNode
    | CascadeSelectorNode
    | null;
  propertyNode: IdentifierNode | null;
  typeArgumentsNode: TypeArgumentsNode | null;
}

export interface CascadeIndexExpressionNode extends AbstractDartNode {
  type: "cascade_index_expression";

  indexNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  objectNode:
    | CascadeCallExpressionNode
    | CascadeIndexExpressionNode
    | CascadeMemberExpressionNode
    | CascadeNullAssertionExpressionNode
    | CascadeNullAwareIndexExpressionNode
    | CascadeNullAwareMemberExpressionNode
    | CascadeSelectorNode;
}

export interface CascadeMemberExpressionNode extends AbstractDartNode {
  type: "cascade_member_expression";

  objectNode:
    | CascadeCallExpressionNode
    | CascadeIndexExpressionNode
    | CascadeMemberExpressionNode
    | CascadeNullAssertionExpressionNode
    | CascadeNullAwareIndexExpressionNode
    | CascadeNullAwareMemberExpressionNode
    | CascadeSelectorNode;
  propertyNode: IdentifierNode;
}

export interface CascadeNullAssertionExpressionNode extends AbstractDartNode {
  type: "cascade_null_assertion_expression";

  valueNode:
    | CascadeCallExpressionNode
    | CascadeIndexExpressionNode
    | CascadeMemberExpressionNode
    | CascadeNullAssertionExpressionNode
    | CascadeNullAwareIndexExpressionNode
    | CascadeNullAwareMemberExpressionNode
    | CascadeSelectorNode;
}

export interface CascadeNullAwareIndexExpressionNode extends AbstractDartNode {
  type: "cascade_null_aware_index_expression";

  indexNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  objectNode:
    | CascadeCallExpressionNode
    | CascadeIndexExpressionNode
    | CascadeMemberExpressionNode
    | CascadeNullAssertionExpressionNode
    | CascadeNullAwareIndexExpressionNode
    | CascadeNullAwareMemberExpressionNode
    | CascadeSelectorNode;
}

export interface CascadeNullAwareMemberExpressionNode extends AbstractDartNode {
  type: "cascade_null_aware_member_expression";

  objectNode:
    | CascadeCallExpressionNode
    | CascadeIndexExpressionNode
    | CascadeMemberExpressionNode
    | CascadeNullAssertionExpressionNode
    | CascadeNullAwareIndexExpressionNode
    | CascadeNullAwareMemberExpressionNode
    | CascadeSelectorNode;
  propertyNode: IdentifierNode;
}

export interface CascadeSectionNode extends AbstractDartNode {
  type: "cascade_section";
}

export interface CascadeSelectorNode extends AbstractDartNode {
  type: "cascade_selector";
}

export interface CastPatternNode extends AbstractDartNode {
  type: "cast_pattern";

  typeNode: TypeNode;
}

export interface CatchClauseNode extends AbstractDartNode {
  type: "catch_clause";

  exceptionNode: IdentifierNode;
  stackTraceNode: IdentifierNode | null;
}

export interface ClassBodyNode extends AbstractDartNode {
  type: "class_body";
}

export interface ClassDeclarationNode extends AbstractDartNode {
  type: "class_declaration";

  bodyNode: ClassBodyNode | null;
  interfacesNode: InterfacesNode | null;
  nameNode: IdentifierNode | null;
  superclassNode: SuperclassNode | null;
  typeParametersNode: TypeParametersNode | null;
}

export interface ClassMemberNode extends AbstractDartNode {
  type: "class_member";
}

export interface CombinatorNode extends AbstractDartNode {
  type: "combinator";
}

export interface CommentNode extends AbstractDartNode {
  type: "comment";
}

export interface ConditionalExpressionNode extends AbstractDartNode {
  type: "conditional_expression";

  alternativeNode:
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode;
  consequenceNode:
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode;
}

export interface ConfigurableUriNode extends AbstractDartNode {
  type: "configurable_uri";
}

export interface ConfigurationUriNode extends AbstractDartNode {
  type: "configuration_uri";
}

export interface ConstObjectExpressionNode extends AbstractDartNode {
  type: "const_object_expression";

  argumentsNode: ArgumentsNode;
  constructorNode: IdentifierNode | null;
  typeNodes: TypeNode[];
}

export interface ConstantConstructorSignatureNode extends AbstractDartNode {
  type: "constant_constructor_signature";

  nameNodes: IdentifierNode[];
  parametersNode: FormalParameterListNode;
}

export interface ConstantPatternNode extends AbstractDartNode {
  type: "constant_pattern";
}

export interface ConstructorInvocationNode extends AbstractDartNode {
  type: "constructor_invocation";

  argumentsNode: ArgumentsNode;
  constructorNode: IdentifierNode | null;
  typeNodes: TypeIdentifierNode[];
}

export interface ConstructorParamNode extends AbstractDartNode {
  type: "constructor_param";
}

export interface ConstructorSignatureNode extends AbstractDartNode {
  type: "constructor_signature";

  nameNodes: IdentifierNode[];
  parametersNode: FormalParameterListNode;
}

export interface ConstructorTearoffNode extends AbstractDartNode {
  type: "constructor_tearoff";
}

export interface ContinueStatementNode extends AbstractDartNode {
  type: "continue_statement";
}

export interface DeclarationNode extends AbstractDartNode {
  type: "declaration";
}

export interface DoStatementNode extends AbstractDartNode {
  type: "do_statement";

  bodyNode: _StatementNode;
  conditionNode: ParenthesizedExpressionNode;
}

export interface DottedIdentifierListNode extends AbstractDartNode {
  type: "dotted_identifier_list";
}

export interface EmptyStatementNode extends AbstractDartNode {
  type: "empty_statement";
}

export interface EnumBodyNode extends AbstractDartNode {
  type: "enum_body";
}

export interface EnumConstantNode extends AbstractDartNode {
  type: "enum_constant";

  nameNode: IdentifierNode;
}

export interface EnumDeclarationNode extends AbstractDartNode {
  type: "enum_declaration";

  bodyNode: EnumBodyNode;
  nameNode: IdentifierNode;
}

export interface EqualityExpressionNode extends AbstractDartNode {
  type: "equality_expression";
}

export interface EscapeSequenceNode extends AbstractDartNode {
  type: "escape_sequence";
}

export interface ExpressionStatementNode extends AbstractDartNode {
  type: "expression_statement";
}

export interface ExtensionBodyNode extends AbstractDartNode {
  type: "extension_body";
}

export interface ExtensionDeclarationNode extends AbstractDartNode {
  type: "extension_declaration";

  bodyNode: ExtensionBodyNode;
  classNode: TypeNode | null;
  nameNode: IdentifierNode | null;
  typeParametersNode: TypeParametersNode | null;
}

export interface ExtensionTypeDeclarationNode extends AbstractDartNode {
  type: "extension_type_declaration";

  bodyNode: ClassBodyNode;
  interfacesNode: InterfacesNode | null;
  nameNode: ExtensionTypeNameNode | IdentifierNode;
  representationNode: ExtensionTypeRepresentationNode | null;
  typeParametersNode: TypeParametersNode | null;
}

export interface ExtensionTypeNameNode extends AbstractDartNode {
  type: "extension_type_name";
}

export interface ExtensionTypeRepresentationNode extends AbstractDartNode {
  type: "extension_type_representation";

  nameNode: IdentifierNode;
  typeNode: TypeNode;
}

export interface ExternalNode extends AbstractDartNode {
  type: "external";
}

export interface ExternalFunctionDeclarationNode extends AbstractDartNode {
  type: "external_function_declaration";

  modifierNode: ExternalNode | null;
  signatureNode: FunctionSignatureNode;
}

export interface ExternalGetterDeclarationNode extends AbstractDartNode {
  type: "external_getter_declaration";

  modifierNode: ExternalNode | null;
  signatureNode: GetterSignatureNode;
}

export interface ExternalSetterDeclarationNode extends AbstractDartNode {
  type: "external_setter_declaration";

  modifierNode: ExternalNode | null;
  signatureNode: SetterSignatureNode;
}

export interface ExternalVariableDeclarationNode extends AbstractDartNode {
  type: "external_variable_declaration";

  modifierNode: ExternalNode;
  typeNode: TypeNode | null;
}

export interface FactoryConstructorSignatureNode extends AbstractDartNode {
  type: "factory_constructor_signature";

  nameNodes: IdentifierNode[];
  parametersNode: FormalParameterListNode;
}

export interface FieldInitializerNode extends AbstractDartNode {
  type: "field_initializer";

  nameNode: IdentifierNode;
  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface FinallyClauseNode extends AbstractDartNode {
  type: "finally_clause";
}

export interface ForElementNode extends AbstractDartNode {
  type: "for_element";

  bodyNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | ForElementNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfElementNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareElementNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | NullAwarePairNode
    | PairNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | SpreadElementNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  conditionNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  initNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LocalVariableDeclarationNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  nameNode: IdentifierNode | null;
  updateNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface ForStatementNode extends AbstractDartNode {
  type: "for_statement";

  bodyNode: _StatementNode;
  conditionNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  initNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LocalVariableDeclarationNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  nameNode: IdentifierNode | null;
  updateNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface FormalParameterNode extends AbstractDartNode {
  type: "formal_parameter";

  nameNode: IdentifierNode | null;
}

export interface FormalParameterListNode extends AbstractDartNode {
  type: "formal_parameter_list";
}

export interface FunctionBodyNode extends AbstractDartNode {
  type: "function_body";
}

export interface FunctionDeclarationNode extends AbstractDartNode {
  type: "function_declaration";

  bodyNode: FunctionBodyNode;
  signatureNode: FunctionSignatureNode;
}

export interface FunctionExpressionNode extends AbstractDartNode {
  type: "function_expression";

  bodyNode: FunctionExpressionBodyNode;
  parametersNodes: (FormalParameterListNode | TypeParametersNode)[];
}

export interface FunctionExpressionBodyNode extends AbstractDartNode {
  type: "function_expression_body";
}

export interface FunctionSignatureNode extends AbstractDartNode {
  type: "function_signature";

  nameNode: IdentifierNode;
  parametersNodes: (FormalParameterListNode | TypeParametersNode)[];
  returnTypeNode: TypeNode | null;
}

export interface FunctionTypeNode extends AbstractDartNode {
  type: "function_type";
}

export interface GetterDeclarationNode extends AbstractDartNode {
  type: "getter_declaration";

  bodyNode: FunctionBodyNode;
  signatureNode: GetterSignatureNode;
}

export interface GetterSignatureNode extends AbstractDartNode {
  type: "getter_signature";

  nameNode: IdentifierNode;
  returnTypeNode: TypeNode | null;
}

export interface IdentifierNode extends AbstractDartNode {
  type: "identifier";
}

export interface IdentifierListNode extends AbstractDartNode {
  type: "identifier_list";
}

export interface IfElementNode extends AbstractDartNode {
  type: "if_element";

  alternativeNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | ForElementNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfElementNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareElementNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | NullAwarePairNode
    | PairNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | SpreadElementNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  conditionNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  consequenceNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | ForElementNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfElementNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareElementNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | NullAwarePairNode
    | PairNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | SpreadElementNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface IfNullExpressionNode extends AbstractDartNode {
  type: "if_null_expression";
}

export interface IfStatementNode extends AbstractDartNode {
  type: "if_statement";

  alternativeNode: _StatementNode | null;
  consequenceNode: _StatementNode;
}

export interface ImportOrExportNode extends AbstractDartNode {
  type: "import_or_export";
}

export interface ImportSpecificationNode extends AbstractDartNode {
  type: "import_specification";

  aliasNode: IdentifierNode | null;
  uriNode: ConfigurableUriNode | UriNode;
}

export interface IndexExpressionNode extends AbstractDartNode {
  type: "index_expression";

  indexNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  objectNode:
    | _InstantiationNode
    | _LiteralNode
    | CallExpressionNode
    | ConstructorTearoffNode
    | FunctionExpressionNode
    | IdentifierNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | MemberExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode;
}

export interface InitializedIdentifierNode extends AbstractDartNode {
  type: "initialized_identifier";

  nameNode: IdentifierNode;
  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface InitializedIdentifierListNode extends AbstractDartNode {
  type: "initialized_identifier_list";
}

export interface InitializedVariableDefinitionNode extends AbstractDartNode {
  type: "initialized_variable_definition";

  nameNode: IdentifierNode;
  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface InitializerListEntryNode extends AbstractDartNode {
  type: "initializer_list_entry";
}

export interface InitializersNode extends AbstractDartNode {
  type: "initializers";
}

export interface InstantiationExpressionNode extends AbstractDartNode {
  type: "instantiation_expression";

  functionNode:
    | _InstantiationNode
    | _LiteralNode
    | CallExpressionNode
    | ConstructorTearoffNode
    | FunctionExpressionNode
    | IdentifierNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | MemberExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode;
  typeArgumentsNode: TypeArgumentsNode;
}

export interface InterfacesNode extends AbstractDartNode {
  type: "interfaces";
}

export interface IsOperatorNode extends AbstractDartNode {
  type: "is_operator";
}

export interface LabelNode extends AbstractDartNode {
  type: "label";
}

export interface LabeledStatementNode extends AbstractDartNode {
  type: "labeled_statement";
}

export interface LibraryExportNode extends AbstractDartNode {
  type: "library_export";

  uriNode: ConfigurableUriNode;
}

export interface LibraryImportNode extends AbstractDartNode {
  type: "library_import";
}

export interface LibraryNameNode extends AbstractDartNode {
  type: "library_name";

  uriNode: UriNode | null;
}

export interface ListLiteralNode extends AbstractDartNode {
  type: "list_literal";
}

export interface ListPatternNode extends AbstractDartNode {
  type: "list_pattern";
}

export interface LocalFunctionDeclarationNode extends AbstractDartNode {
  type: "local_function_declaration";
}

export interface LocalVariableDeclarationNode extends AbstractDartNode {
  type: "local_variable_declaration";
}

export interface LogicalAndExpressionNode extends AbstractDartNode {
  type: "logical_and_expression";
}

export interface LogicalOrExpressionNode extends AbstractDartNode {
  type: "logical_or_expression";
}

export interface MapPatternNode extends AbstractDartNode {
  type: "map_pattern";
}

export interface MemberExpressionNode extends AbstractDartNode {
  type: "member_expression";

  objectNode:
    | _InstantiationNode
    | _LiteralNode
    | CallExpressionNode
    | ConstructorTearoffNode
    | FunctionExpressionNode
    | IdentifierNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | MemberExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode;
  propertyNode: IdentifierNode;
}

export interface MethodDeclarationNode extends AbstractDartNode {
  type: "method_declaration";

  bodyNode: FunctionBodyNode;
  signatureNode: MethodSignatureNode;
}

export interface MethodSignatureNode extends AbstractDartNode {
  type: "method_signature";
}

export interface MixinApplicationNode extends AbstractDartNode {
  type: "mixin_application";
}

export interface MixinApplicationClassNode extends AbstractDartNode {
  type: "mixin_application_class";
}

export interface MixinDeclarationNode extends AbstractDartNode {
  type: "mixin_declaration";

  bodyNode: ClassBodyNode;
  interfacesNode: InterfacesNode | null;
  nameNode: IdentifierNode;
  typeParametersNode: TypeParametersNode | null;
}

export interface MixinsNode extends AbstractDartNode {
  type: "mixins";
}

export interface MultiplicativeExpressionNode extends AbstractDartNode {
  type: "multiplicative_expression";
}

export interface NamedArgumentNode extends AbstractDartNode {
  type: "named_argument";
}

export interface NamedParameterTypesNode extends AbstractDartNode {
  type: "named_parameter_types";
}

export interface NativeNode extends AbstractDartNode {
  type: "native";
}

export interface NegateOperatorNode extends AbstractDartNode {
  type: "negate_operator";
}

export interface NewExpressionNode extends AbstractDartNode {
  type: "new_expression";

  argumentsNode: ArgumentsNode;
  constructorNode: IdentifierNode | null;
  typeNodes: TypeNode[];
}

export interface NormalParameterTypeNode extends AbstractDartNode {
  type: "normal_parameter_type";
}

export interface NullAssertPatternNode extends AbstractDartNode {
  type: "null_assert_pattern";
}

export interface NullAssertionExpressionNode extends AbstractDartNode {
  type: "null_assertion_expression";

  valueNode:
    | _InstantiationNode
    | _LiteralNode
    | CallExpressionNode
    | ConstructorTearoffNode
    | FunctionExpressionNode
    | IdentifierNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | MemberExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode;
}

export interface NullAwareElementNode extends AbstractDartNode {
  type: "null_aware_element";
}

export interface NullAwareIndexExpressionNode extends AbstractDartNode {
  type: "null_aware_index_expression";

  indexNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  objectNode:
    | _InstantiationNode
    | _LiteralNode
    | CallExpressionNode
    | ConstructorTearoffNode
    | FunctionExpressionNode
    | IdentifierNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | MemberExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode;
}

export interface NullAwareMemberExpressionNode extends AbstractDartNode {
  type: "null_aware_member_expression";

  objectNode:
    | _InstantiationNode
    | _LiteralNode
    | CallExpressionNode
    | ConstructorTearoffNode
    | FunctionExpressionNode
    | IdentifierNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | MemberExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode;
  propertyNode: IdentifierNode;
}

export interface NullAwarePairNode extends AbstractDartNode {
  type: "null_aware_pair";

  keyNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareElementNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface NullCheckPatternNode extends AbstractDartNode {
  type: "null_check_pattern";
}

export interface ObjectPatternNode extends AbstractDartNode {
  type: "object_pattern";
}

export interface OperatorSignatureNode extends AbstractDartNode {
  type: "operator_signature";

  operatorNode: BinaryOperatorNode;
  parametersNode: FormalParameterListNode;
  returnTypeNode: TypeNode | null;
}

export interface OptionalFormalParametersNode extends AbstractDartNode {
  type: "optional_formal_parameters";
}

export interface OptionalParameterTypesNode extends AbstractDartNode {
  type: "optional_parameter_types";
}

export interface OptionalPositionalParameterTypesNode extends AbstractDartNode {
  type: "optional_positional_parameter_types";
}

export interface PairNode extends AbstractDartNode {
  type: "pair";

  keyNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareElementNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface ParameterTypeListNode extends AbstractDartNode {
  type: "parameter_type_list";
}

export interface ParenthesizedExpressionNode extends AbstractDartNode {
  type: "parenthesized_expression";
}

export interface PartDirectiveNode extends AbstractDartNode {
  type: "part_directive";

  uriNode: UriNode;
}

export interface PartOfDirectiveNode extends AbstractDartNode {
  type: "part_of_directive";
}

export interface PatternAssignmentNode extends AbstractDartNode {
  type: "pattern_assignment";
}

export interface PatternVariableDeclarationNode extends AbstractDartNode {
  type: "pattern_variable_declaration";
}

export interface PostfixExpressionNode extends AbstractDartNode {
  type: "postfix_expression";

  argumentNode: AssignableExpressionNode;
}

export interface PrefixOperatorNode extends AbstractDartNode {
  type: "prefix_operator";
}

export interface QualifiedNode extends AbstractDartNode {
  type: "qualified";
}

export interface RawStringLiteralDoubleQuotesNode extends AbstractDartNode {
  type: "raw_string_literal_double_quotes";
}

export interface RawStringLiteralDoubleQuotesMultipleNode extends AbstractDartNode {
  type: "raw_string_literal_double_quotes_multiple";
}

export interface RawStringLiteralSingleQuotesNode extends AbstractDartNode {
  type: "raw_string_literal_single_quotes";
}

export interface RawStringLiteralSingleQuotesMultipleNode extends AbstractDartNode {
  type: "raw_string_literal_single_quotes_multiple";
}

export interface RecordFieldNode extends AbstractDartNode {
  type: "record_field";
}

export interface RecordLiteralNode extends AbstractDartNode {
  type: "record_literal";
}

export interface RecordPatternNode extends AbstractDartNode {
  type: "record_pattern";
}

export interface RecordTypeNode extends AbstractDartNode {
  type: "record_type";
}

export interface RecordTypeFieldNode extends AbstractDartNode {
  type: "record_type_field";

  nameNode: IdentifierNode | null;
  typeNode: TypeNode;
}

export interface RecordTypeNamedFieldNode extends AbstractDartNode {
  type: "record_type_named_field";
}

export interface RedirectingFactoryConstructorSignatureNode extends AbstractDartNode {
  type: "redirecting_factory_constructor_signature";

  nameNodes: IdentifierNode[];
  parametersNode: FormalParameterListNode;
  targetNodes: TypeNode[];
  targetConstructorNode: IdentifierNode | null;
}

export interface RedirectionNode extends AbstractDartNode {
  type: "redirection";
}

export interface RelationalExpressionNode extends AbstractDartNode {
  type: "relational_expression";
}

export interface RelationalOperatorNode extends AbstractDartNode {
  type: "relational_operator";
}

export interface RestPatternNode extends AbstractDartNode {
  type: "rest_pattern";
}

export interface RethrowStatementNode extends AbstractDartNode {
  type: "rethrow_statement";
}

export interface ReturnStatementNode extends AbstractDartNode {
  type: "return_statement";
}

export interface ScriptTagNode extends AbstractDartNode {
  type: "script_tag";
}

export interface SetOrMapLiteralNode extends AbstractDartNode {
  type: "set_or_map_literal";
}

export interface SetterDeclarationNode extends AbstractDartNode {
  type: "setter_declaration";

  bodyNode: FunctionBodyNode;
  signatureNode: SetterSignatureNode;
}

export interface SetterSignatureNode extends AbstractDartNode {
  type: "setter_signature";

  nameNode: IdentifierNode;
  parametersNodes: (FormalParameterListNode | TypeParametersNode)[];
  returnTypeNode: TypeNode | null;
}

export interface ShiftExpressionNode extends AbstractDartNode {
  type: "shift_expression";
}

export interface SourceFileNode extends AbstractDartNode {
  type: "source_file";
}

export interface SpreadElementNode extends AbstractDartNode {
  type: "spread_element";

  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface StaticFinalDeclarationNode extends AbstractDartNode {
  type: "static_final_declaration";

  nameNode: IdentifierNode;
  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface StaticFinalDeclarationListNode extends AbstractDartNode {
  type: "static_final_declaration_list";
}

export interface StaticMemberShorthandNode extends AbstractDartNode {
  type: "static_member_shorthand";
}

export interface StringLiteralNode extends AbstractDartNode {
  type: "string_literal";
}

export interface StringLiteralDoubleQuotesNode extends AbstractDartNode {
  type: "string_literal_double_quotes";
}

export interface StringLiteralDoubleQuotesMultipleNode extends AbstractDartNode {
  type: "string_literal_double_quotes_multiple";
}

export interface StringLiteralSingleQuotesNode extends AbstractDartNode {
  type: "string_literal_single_quotes";
}

export interface StringLiteralSingleQuotesMultipleNode extends AbstractDartNode {
  type: "string_literal_single_quotes_multiple";
}

export interface SuperFormalParameterNode extends AbstractDartNode {
  type: "super_formal_parameter";
}

export interface SuperclassNode extends AbstractDartNode {
  type: "superclass";

  typeNodes: TypeNode[];
}

export interface SwitchBlockNode extends AbstractDartNode {
  type: "switch_block";
}

export interface SwitchExpressionNode extends AbstractDartNode {
  type: "switch_expression";

  bodyNodes: SwitchExpressionCaseNode[];
  conditionNode: ParenthesizedExpressionNode;
}

export interface SwitchExpressionCaseNode extends AbstractDartNode {
  type: "switch_expression_case";
}

export interface SwitchStatementNode extends AbstractDartNode {
  type: "switch_statement";

  bodyNode: SwitchBlockNode;
  conditionNode: ParenthesizedExpressionNode;
}

export interface SwitchStatementCaseNode extends AbstractDartNode {
  type: "switch_statement_case";
}

export interface SwitchStatementDefaultNode extends AbstractDartNode {
  type: "switch_statement_default";
}

export interface SymbolLiteralNode extends AbstractDartNode {
  type: "symbol_literal";
}

export interface TemplateSubstitutionNode extends AbstractDartNode {
  type: "template_substitution";
}

export interface ThrowExpressionNode extends AbstractDartNode {
  type: "throw_expression";

  valueNodes: (
    | _InstantiationNode
    | _LiteralNode
    | AdditiveExpressionNode
    | AssignmentExpressionNode
    | BitwiseAndExpressionNode
    | BitwiseOrExpressionNode
    | BitwiseXorExpressionNode
    | CallExpressionNode
    | CascadeSectionNode
    | ConditionalExpressionNode
    | ConstructorTearoffNode
    | EqualityExpressionNode
    | FunctionExpressionNode
    | IdentifierNode
    | IfNullExpressionNode
    | IndexExpressionNode
    | InstantiationExpressionNode
    | LogicalAndExpressionNode
    | LogicalOrExpressionNode
    | MemberExpressionNode
    | MultiplicativeExpressionNode
    | NullAssertionExpressionNode
    | NullAwareIndexExpressionNode
    | NullAwareMemberExpressionNode
    | ParenthesizedExpressionNode
    | PatternAssignmentNode
    | PostfixExpressionNode
    | RelationalExpressionNode
    | ShiftExpressionNode
    | StaticMemberShorthandNode
    | SwitchExpressionNode
    | ThrowExpressionNode
    | TypeCastExpressionNode
    | TypeTestExpressionNode
    | UnaryExpressionNode
  )[];
}

export interface TopLevelVariableDeclarationNode extends AbstractDartNode {
  type: "top_level_variable_declaration";

  modifierNode: AbstractDartNode;
  typeNode: TypeNode | null;
}

export interface TryStatementNode extends AbstractDartNode {
  type: "try_statement";

  bodyNode: BlockNode;
}

export interface TypeNode extends AbstractDartNode {
  type: "type";
}

export interface TypeAliasNode extends AbstractDartNode {
  type: "type_alias";
}

export interface TypeArgumentsNode extends AbstractDartNode {
  type: "type_arguments";
}

export interface TypeCastNode extends AbstractDartNode {
  type: "type_cast";
}

export interface TypeCastExpressionNode extends AbstractDartNode {
  type: "type_cast_expression";
}

export interface TypeIdentifierNode extends AbstractDartNode {
  type: "type_identifier";
}

export interface TypeParameterNode extends AbstractDartNode {
  type: "type_parameter";

  boundNodes: TypeNode[];
  nameNode: TypeIdentifierNode;
  varianceNode: VarianceModifierNode | null;
}

export interface TypeParametersNode extends AbstractDartNode {
  type: "type_parameters";
}

export interface TypeTestNode extends AbstractDartNode {
  type: "type_test";
}

export interface TypeTestExpressionNode extends AbstractDartNode {
  type: "type_test_expression";
}

export interface TypedIdentifierNode extends AbstractDartNode {
  type: "typed_identifier";

  nameNode: IdentifierNode;
  typeNode: TypeNode;
}

export interface UnaryExpressionNode extends AbstractDartNode {
  type: "unary_expression";
}

export interface UriNode extends AbstractDartNode {
  type: "uri";
}

export interface UriTestNode extends AbstractDartNode {
  type: "uri_test";
}

export interface VariablePatternNode extends AbstractDartNode {
  type: "variable_pattern";

  nameNode: IdentifierNode;
}

export interface VarianceModifierNode extends AbstractDartNode {
  type: "variance_modifier";
}

export interface WhileStatementNode extends AbstractDartNode {
  type: "while_statement";

  bodyNode: _StatementNode;
  conditionNode: ParenthesizedExpressionNode;
}

export interface YieldEachStatementNode extends AbstractDartNode {
  type: "yield_each_statement";
}

export interface YieldStatementNode extends AbstractDartNode {
  type: "yield_statement";
}

export interface AnnotationOpenParenNode extends AbstractDartNode {
  type: "annotation_open_paren";
}

export interface BlockCommentNode extends AbstractDartNode {
  type: "block_comment";
}

export interface DecimalFloatingPointLiteralNode extends AbstractDartNode {
  type: "decimal_floating_point_literal";
}

export interface DecimalIntegerLiteralNode extends AbstractDartNode {
  type: "decimal_integer_literal";
}

export interface DocumentationBlockCommentNode extends AbstractDartNode {
  type: "documentation_block_comment";
}

export interface FalseNode extends AbstractDartNode {
  type: "false";
}

export interface HexIntegerLiteralNode extends AbstractDartNode {
  type: "hex_integer_literal";
}

export interface IdentifierDollarEscapedNode extends AbstractDartNode {
  type: "identifier_dollar_escaped";
}

export interface NullLiteralNode extends AbstractDartNode {
  type: "null_literal";
}

export interface TemplateCharsDoubleNode extends AbstractDartNode {
  type: "template_chars_double";
}

export interface TemplateCharsDoubleSingleNode extends AbstractDartNode {
  type: "template_chars_double_single";
}

export interface TemplateCharsRawSlashNode extends AbstractDartNode {
  type: "template_chars_raw_slash";
}

export interface TemplateCharsSingleNode extends AbstractDartNode {
  type: "template_chars_single";
}

export interface TemplateCharsSingleSingleNode extends AbstractDartNode {
  type: "template_chars_single_single";
}

export interface TrueNode extends AbstractDartNode {
  type: "true";
}

export interface VoidTypeNode extends AbstractDartNode {
  type: "void_type";
}

export type DartNode =
  | AdditiveExpressionNode
  | AnnotationNode
  | AnnotationArgumentsNode
  | ArgumentsNode
  | AssertStatementNode
  | AssertionNode
  | AssignableExpressionNode
  | AssignmentExpressionNode
  | AwaitExpressionNode
  | BinaryOperatorNode
  | BitwiseAndExpressionNode
  | BitwiseOrExpressionNode
  | BitwiseXorExpressionNode
  | BlockNode
  | BreakStatementNode
  | CallExpressionNode
  | CascadeCallExpressionNode
  | CascadeIndexExpressionNode
  | CascadeMemberExpressionNode
  | CascadeNullAssertionExpressionNode
  | CascadeNullAwareIndexExpressionNode
  | CascadeNullAwareMemberExpressionNode
  | CascadeSectionNode
  | CascadeSelectorNode
  | CastPatternNode
  | CatchClauseNode
  | ClassBodyNode
  | ClassDeclarationNode
  | ClassMemberNode
  | CombinatorNode
  | CommentNode
  | ConditionalExpressionNode
  | ConfigurableUriNode
  | ConfigurationUriNode
  | ConstObjectExpressionNode
  | ConstantConstructorSignatureNode
  | ConstantPatternNode
  | ConstructorInvocationNode
  | ConstructorParamNode
  | ConstructorSignatureNode
  | ConstructorTearoffNode
  | ContinueStatementNode
  | DeclarationNode
  | DoStatementNode
  | DottedIdentifierListNode
  | EmptyStatementNode
  | EnumBodyNode
  | EnumConstantNode
  | EnumDeclarationNode
  | EqualityExpressionNode
  | EscapeSequenceNode
  | ExpressionStatementNode
  | ExtensionBodyNode
  | ExtensionDeclarationNode
  | ExtensionTypeDeclarationNode
  | ExtensionTypeNameNode
  | ExtensionTypeRepresentationNode
  | ExternalNode
  | ExternalFunctionDeclarationNode
  | ExternalGetterDeclarationNode
  | ExternalSetterDeclarationNode
  | ExternalVariableDeclarationNode
  | FactoryConstructorSignatureNode
  | FieldInitializerNode
  | FinallyClauseNode
  | ForElementNode
  | ForStatementNode
  | FormalParameterNode
  | FormalParameterListNode
  | FunctionBodyNode
  | FunctionDeclarationNode
  | FunctionExpressionNode
  | FunctionExpressionBodyNode
  | FunctionSignatureNode
  | FunctionTypeNode
  | GetterDeclarationNode
  | GetterSignatureNode
  | IdentifierNode
  | IdentifierListNode
  | IfElementNode
  | IfNullExpressionNode
  | IfStatementNode
  | ImportOrExportNode
  | ImportSpecificationNode
  | IndexExpressionNode
  | InitializedIdentifierNode
  | InitializedIdentifierListNode
  | InitializedVariableDefinitionNode
  | InitializerListEntryNode
  | InitializersNode
  | InstantiationExpressionNode
  | InterfacesNode
  | IsOperatorNode
  | LabelNode
  | LabeledStatementNode
  | LibraryExportNode
  | LibraryImportNode
  | LibraryNameNode
  | ListLiteralNode
  | ListPatternNode
  | LocalFunctionDeclarationNode
  | LocalVariableDeclarationNode
  | LogicalAndExpressionNode
  | LogicalOrExpressionNode
  | MapPatternNode
  | MemberExpressionNode
  | MethodDeclarationNode
  | MethodSignatureNode
  | MixinApplicationNode
  | MixinApplicationClassNode
  | MixinDeclarationNode
  | MixinsNode
  | MultiplicativeExpressionNode
  | NamedArgumentNode
  | NamedParameterTypesNode
  | NativeNode
  | NegateOperatorNode
  | NewExpressionNode
  | NormalParameterTypeNode
  | NullAssertPatternNode
  | NullAssertionExpressionNode
  | NullAwareElementNode
  | NullAwareIndexExpressionNode
  | NullAwareMemberExpressionNode
  | NullAwarePairNode
  | NullCheckPatternNode
  | ObjectPatternNode
  | OperatorSignatureNode
  | OptionalFormalParametersNode
  | OptionalParameterTypesNode
  | OptionalPositionalParameterTypesNode
  | PairNode
  | ParameterTypeListNode
  | ParenthesizedExpressionNode
  | PartDirectiveNode
  | PartOfDirectiveNode
  | PatternAssignmentNode
  | PatternVariableDeclarationNode
  | PostfixExpressionNode
  | PrefixOperatorNode
  | QualifiedNode
  | RawStringLiteralDoubleQuotesNode
  | RawStringLiteralDoubleQuotesMultipleNode
  | RawStringLiteralSingleQuotesNode
  | RawStringLiteralSingleQuotesMultipleNode
  | RecordFieldNode
  | RecordLiteralNode
  | RecordPatternNode
  | RecordTypeNode
  | RecordTypeFieldNode
  | RecordTypeNamedFieldNode
  | RedirectingFactoryConstructorSignatureNode
  | RedirectionNode
  | RelationalExpressionNode
  | RelationalOperatorNode
  | RestPatternNode
  | RethrowStatementNode
  | ReturnStatementNode
  | ScriptTagNode
  | SetOrMapLiteralNode
  | SetterDeclarationNode
  | SetterSignatureNode
  | ShiftExpressionNode
  | SourceFileNode
  | SpreadElementNode
  | StaticFinalDeclarationNode
  | StaticFinalDeclarationListNode
  | StaticMemberShorthandNode
  | StringLiteralNode
  | StringLiteralDoubleQuotesNode
  | StringLiteralDoubleQuotesMultipleNode
  | StringLiteralSingleQuotesNode
  | StringLiteralSingleQuotesMultipleNode
  | SuperFormalParameterNode
  | SuperclassNode
  | SwitchBlockNode
  | SwitchExpressionNode
  | SwitchExpressionCaseNode
  | SwitchStatementNode
  | SwitchStatementCaseNode
  | SwitchStatementDefaultNode
  | SymbolLiteralNode
  | TemplateSubstitutionNode
  | ThrowExpressionNode
  | TopLevelVariableDeclarationNode
  | TryStatementNode
  | TypeNode
  | TypeAliasNode
  | TypeArgumentsNode
  | TypeCastNode
  | TypeCastExpressionNode
  | TypeIdentifierNode
  | TypeParameterNode
  | TypeParametersNode
  | TypeTestNode
  | TypeTestExpressionNode
  | TypedIdentifierNode
  | UnaryExpressionNode
  | UriNode
  | UriTestNode
  | VariablePatternNode
  | VarianceModifierNode
  | WhileStatementNode
  | YieldEachStatementNode
  | YieldStatementNode
  | AnnotationOpenParenNode
  | BlockCommentNode
  | DecimalFloatingPointLiteralNode
  | DecimalIntegerLiteralNode
  | DocumentationBlockCommentNode
  | FalseNode
  | HexIntegerLiteralNode
  | IdentifierDollarEscapedNode
  | NullLiteralNode
  | TemplateCharsDoubleNode
  | TemplateCharsDoubleSingleNode
  | TemplateCharsRawSlashNode
  | TemplateCharsSingleNode
  | TemplateCharsSingleSingleNode
  | TrueNode
  | VoidTypeNode;
