/* Autogenerated, do not edit by hand. */
/* eslint-disable max-lines */

import type { SyntaxNode, Point } from "tree-sitter";

export interface AbstractVb_dotnetNode extends SyntaxNode {
  parent: Vb_dotnetNode | null;
  namedChildren: Array<Vb_dotnetNode>;

  descendantsOfType(
    types: string | Array<string>,
    startPosition?: Point,
    endPosition?: Point,
  ): Array<Vb_dotnetNode>;
}

export interface AddHandlerBlockNode extends AbstractVb_dotnetNode {
  type: "add_handler_block";

  modifiersNode: ModifiersNode | null;
}

export interface ArgumentNode extends AbstractVb_dotnetNode {
  type: "argument";

  nameNode: IdentifierNode | null;
}

export interface ArgumentListNode extends AbstractVb_dotnetNode {
  type: "argument_list";
}

export interface ArrayLiteralNode extends AbstractVb_dotnetNode {
  type: "array_literal";
}

export interface ArrayRankSpecifierNode extends AbstractVb_dotnetNode {
  type: "array_rank_specifier";
}

export interface ArrayTypeNode extends AbstractVb_dotnetNode {
  type: "array_type";
}

export interface AsClauseNode extends AbstractVb_dotnetNode {
  type: "as_clause";

  typeNode: TypeNode;
}

export interface AssignmentStatementNode extends AbstractVb_dotnetNode {
  type: "assignment_statement";

  leftNode: LeftHandSideNode;
  rightNode: ExpressionNode;
}

export interface AttributeNode extends AbstractVb_dotnetNode {
  type: "attribute";

  nameNode: IdentifierNode | NamespaceNameNode;
  targetNode: IdentifierNode | null;
}

export interface AttributeBlockNode extends AbstractVb_dotnetNode {
  type: "attribute_block";
}

export interface BinaryExpressionNode extends AbstractVb_dotnetNode {
  type: "binary_expression";

  leftNode: ExpressionNode;
  operatorNode: AbstractVb_dotnetNode;
  rightNode: ExpressionNode;
}

export interface BlankLineNode extends AbstractVb_dotnetNode {
  type: "blank_line";
}

export interface CallStatementNode extends AbstractVb_dotnetNode {
  type: "call_statement";
}

export interface CaseBlockNode extends AbstractVb_dotnetNode {
  type: "case_block";
}

export interface CaseClauseNode extends AbstractVb_dotnetNode {
  type: "case_clause";
}

export interface CaseElseBlockNode extends AbstractVb_dotnetNode {
  type: "case_else_block";
}

export interface CatchBlockNode extends AbstractVb_dotnetNode {
  type: "catch_block";

  exceptionNode: IdentifierNode | null;
  filterNode: ExpressionNode | null;
  typeNode: TypeNode | null;
}

export interface ClassBlockNode extends AbstractVb_dotnetNode {
  type: "class_block";

  implementsNode: ImplementsClauseNode | null;
  inheritsNode: InheritsClauseNode | null;
  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
}

export interface CompoundAssignmentStatementNode extends AbstractVb_dotnetNode {
  type: "compound_assignment_statement";

  leftNode: LeftHandSideNode;
  operatorNode: AbstractVb_dotnetNode;
  rightNode: ExpressionNode;
}

export interface ConstDeclarationNode extends AbstractVb_dotnetNode {
  type: "const_declaration";

  attributesNode: AttributeBlockNode | null;
  modifiersNode: ModifiersNode | null;
  nameNodes: IdentifierNode[];
  valueNodes: ExpressionNode[];
}

export interface ConstructorDeclarationNode extends AbstractVb_dotnetNode {
  type: "constructor_declaration";

  attributesNode: AttributeBlockNode | null;
  modifiersNode: ModifiersNode | null;
  parametersNode: ParameterListNode;
}

export interface ContinueStatementNode extends AbstractVb_dotnetNode {
  type: "continue_statement";
}

export interface DelegateDeclarationNode extends AbstractVb_dotnetNode {
  type: "delegate_declaration";

  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
  parametersNode: ParameterListNode;
  returnTypeNode: TypeNode | null;
}

export interface DimStatementNode extends AbstractVb_dotnetNode {
  type: "dim_statement";

  initializerNodes: ExpressionNode[];
  nameNodes: IdentifierNode[];
}

export interface DoStatementNode extends AbstractVb_dotnetNode {
  type: "do_statement";
}

export interface ElementAccessNode extends AbstractVb_dotnetNode {
  type: "element_access";

  indexNodes: ExpressionNode[];
  objectNode: ExpressionNode;
}

export interface ElseClauseNode extends AbstractVb_dotnetNode {
  type: "else_clause";
}

export interface ElseifClauseNode extends AbstractVb_dotnetNode {
  type: "elseif_clause";

  conditionNode: ExpressionNode;
}

export interface EmptyStatementNode extends AbstractVb_dotnetNode {
  type: "empty_statement";
}

export interface EnumBlockNode extends AbstractVb_dotnetNode {
  type: "enum_block";

  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
}

export interface EnumMemberNode extends AbstractVb_dotnetNode {
  type: "enum_member";

  nameNode: IdentifierNode;
  valueNode: ExpressionNode | null;
}

export interface EventDeclarationNode extends AbstractVb_dotnetNode {
  type: "event_declaration";

  attributesNode: AttributeBlockNode | null;
  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
}

export interface ExitStatementNode extends AbstractVb_dotnetNode {
  type: "exit_statement";
}

export interface ExpressionNode extends AbstractVb_dotnetNode {
  type: "expression";
}

export interface FieldDeclarationNode extends AbstractVb_dotnetNode {
  type: "field_declaration";

  attributesNode: AttributeBlockNode | null;
  modifiersNode: ModifiersNode | null;
}

export interface FinallyBlockNode extends AbstractVb_dotnetNode {
  type: "finally_block";
}

export interface ForEachStatementNode extends AbstractVb_dotnetNode {
  type: "for_each_statement";

  collectionNode: ExpressionNode;
  variableNodes: IdentifierNode[];
}

export interface ForStatementNode extends AbstractVb_dotnetNode {
  type: "for_statement";

  endNode: ExpressionNode;
  startNode: ExpressionNode;
  stepNode: ExpressionNode | null;
  variableNodes: IdentifierNode[];
}

export interface GenericTypeNode extends AbstractVb_dotnetNode {
  type: "generic_type";
}

export interface GetAccessorNode extends AbstractVb_dotnetNode {
  type: "get_accessor";

  modifiersNode: ModifiersNode | null;
}

export interface GotoStatementNode extends AbstractVb_dotnetNode {
  type: "goto_statement";

  labelNode: IdentifierNode;
}

export interface IfStatementNode extends AbstractVb_dotnetNode {
  type: "if_statement";

  conditionNode: ExpressionNode;
  elseBranchNode: ExpressionNode | StatementNode | null;
  thenBranchNode: ExpressionNode | StatementNode | null;
}

export interface ImplementsClauseNode extends AbstractVb_dotnetNode {
  type: "implements_clause";
}

export interface ImportsStatementNode extends AbstractVb_dotnetNode {
  type: "imports_statement";

  namespaceNodes: NamespaceNameNode[];
}

export interface InheritsClauseNode extends AbstractVb_dotnetNode {
  type: "inherits_clause";
}

export interface InterfaceBlockNode extends AbstractVb_dotnetNode {
  type: "interface_block";

  inheritsNode: InheritsClauseNode | null;
  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
}

export interface InterpolatedStringLiteralNode extends AbstractVb_dotnetNode {
  type: "interpolated_string_literal";
}

export interface InterpolationNode extends AbstractVb_dotnetNode {
  type: "interpolation";
}

export interface InvocationNode extends AbstractVb_dotnetNode {
  type: "invocation";

  argumentsNode: ArgumentListNode;
  targetNode: IdentifierNode | MemberAccessNode;
}

export interface LabelStatementNode extends AbstractVb_dotnetNode {
  type: "label_statement";

  labelNode: IdentifierNode;
}

export interface LambdaExpressionNode extends AbstractVb_dotnetNode {
  type: "lambda_expression";
}

export interface LambdaParameterNode extends AbstractVb_dotnetNode {
  type: "lambda_parameter";

  nameNode: IdentifierNode;
}

export interface LeftHandSideNode extends AbstractVb_dotnetNode {
  type: "left_hand_side";
}

export interface LiteralNode extends AbstractVb_dotnetNode {
  type: "literal";
}

export interface MemberAccessNode extends AbstractVb_dotnetNode {
  type: "member_access";

  memberNode: IdentifierNode;
  objectNode: ExpressionNode;
}

export interface MemberInitializerNode extends AbstractVb_dotnetNode {
  type: "member_initializer";

  memberNode: IdentifierNode;
  valueNode: ExpressionNode;
}

export interface MethodDeclarationNode extends AbstractVb_dotnetNode {
  type: "method_declaration";

  attributesNode: AttributeBlockNode | null;
  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
  parametersNode: ParameterListNode;
  returnTypeNode: TypeNode | null;
}

export interface ModifiersNode extends AbstractVb_dotnetNode {
  type: "modifiers";
}

export interface ModuleBlockNode extends AbstractVb_dotnetNode {
  type: "module_block";

  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
}

export interface NamespaceBlockNode extends AbstractVb_dotnetNode {
  type: "namespace_block";

  nameNode: NamespaceNameNode;
}

export interface NamespaceNameNode extends AbstractVb_dotnetNode {
  type: "namespace_name";
}

export interface NewExpressionNode extends AbstractVb_dotnetNode {
  type: "new_expression";

  typeNode: TypeNode;
}

export interface ObjectInitializerNode extends AbstractVb_dotnetNode {
  type: "object_initializer";
}

export interface ObjectInitializersNode extends AbstractVb_dotnetNode {
  type: "object_initializers";
}

export interface OptionStatementsNode extends AbstractVb_dotnetNode {
  type: "option_statements";
}

export interface ParameterNode extends AbstractVb_dotnetNode {
  type: "parameter";

  defaultValueNode: ExpressionNode | null;
  nameNode: IdentifierNode;
}

export interface ParameterListNode extends AbstractVb_dotnetNode {
  type: "parameter_list";
}

export interface ParenthesizedExpressionNode extends AbstractVb_dotnetNode {
  type: "parenthesized_expression";
}

export interface PropertyDeclarationNode extends AbstractVb_dotnetNode {
  type: "property_declaration";

  attributesNode: AttributeBlockNode | null;
  initializerNode: ExpressionNode | null;
  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
  parametersNode: ParameterListNode | null;
}

export interface RaiseEventBlockNode extends AbstractVb_dotnetNode {
  type: "raise_event_block";

  modifiersNode: ModifiersNode | null;
}

export interface ReDimClauseNode extends AbstractVb_dotnetNode {
  type: "re_dim_clause";

  upperBoundNode: ExpressionNode;
}

export interface RedimStatementNode extends AbstractVb_dotnetNode {
  type: "redim_statement";

  arrayNodes: IdentifierNode[];
}

export interface RemoveHandlerBlockNode extends AbstractVb_dotnetNode {
  type: "remove_handler_block";

  modifiersNode: ModifiersNode | null;
}

export interface ReturnStatementNode extends AbstractVb_dotnetNode {
  type: "return_statement";
}

export interface SelectCaseStatementNode extends AbstractVb_dotnetNode {
  type: "select_case_statement";

  selectorNode: ExpressionNode;
}

export interface SetAccessorNode extends AbstractVb_dotnetNode {
  type: "set_accessor";

  modifiersNode: ModifiersNode | null;
  parametersNode: ParameterListNode | null;
}

export interface SourceFileNode extends AbstractVb_dotnetNode {
  type: "source_file";
}

export interface StatementNode extends AbstractVb_dotnetNode {
  type: "statement";
}

export interface StringLiteralNode extends AbstractVb_dotnetNode {
  type: "string_literal";
}

export interface StructureBlockNode extends AbstractVb_dotnetNode {
  type: "structure_block";

  implementsNode: ImplementsClauseNode | null;
  modifiersNode: ModifiersNode | null;
  nameNode: IdentifierNode;
}

export interface SyncLockStatementNode extends AbstractVb_dotnetNode {
  type: "sync_lock_statement";

  lockNode: ExpressionNode;
}

export interface TernaryExpressionNode extends AbstractVb_dotnetNode {
  type: "ternary_expression";

  conditionNode: ExpressionNode;
  falseBranchNode: ExpressionNode;
  trueBranchNode: ExpressionNode;
}

export interface ThrowStatementNode extends AbstractVb_dotnetNode {
  type: "throw_statement";
}

export interface TryStatementNode extends AbstractVb_dotnetNode {
  type: "try_statement";
}

export interface TypeNode extends AbstractVb_dotnetNode {
  type: "type";
}

export interface TypeArgumentListNode extends AbstractVb_dotnetNode {
  type: "type_argument_list";
}

export interface TypeConstraintNode extends AbstractVb_dotnetNode {
  type: "type_constraint";
}

export interface TypeDeclarationNode extends AbstractVb_dotnetNode {
  type: "type_declaration";
}

export interface TypeParameterNode extends AbstractVb_dotnetNode {
  type: "type_parameter";

  constraintNode: TypeConstraintNode | null;
  nameNode: IdentifierNode;
}

export interface TypeParametersNode extends AbstractVb_dotnetNode {
  type: "type_parameters";
}

export interface UnaryExpressionNode extends AbstractVb_dotnetNode {
  type: "unary_expression";

  operandNode: ExpressionNode;
  operatorNode: AbstractVb_dotnetNode;
}

export interface UsingStatementNode extends AbstractVb_dotnetNode {
  type: "using_statement";

  resourceNode: IdentifierNode | null;
  valueNode: ExpressionNode;
}

export interface VariableDeclaratorNode extends AbstractVb_dotnetNode {
  type: "variable_declarator";

  initializerNode: ExpressionNode | null;
  nameNode: IdentifierNode;
}

export interface WhileStatementNode extends AbstractVb_dotnetNode {
  type: "while_statement";

  conditionNode: ExpressionNode;
}

export interface WithInitializerNode extends AbstractVb_dotnetNode {
  type: "with_initializer";
}

export interface WithStatementNode extends AbstractVb_dotnetNode {
  type: "with_statement";

  targetNode: ExpressionNode;
}

export interface BooleanLiteralNode extends AbstractVb_dotnetNode {
  type: "boolean_literal";
}

export interface CharacterLiteralNode extends AbstractVb_dotnetNode {
  type: "character_literal";
}

export interface CommentNode extends AbstractVb_dotnetNode {
  type: "comment";
}

export interface DateLiteralNode extends AbstractVb_dotnetNode {
  type: "date_literal";
}

export interface FloatingPointLiteralNode extends AbstractVb_dotnetNode {
  type: "floating_point_literal";
}

export interface IdentifierNode extends AbstractVb_dotnetNode {
  type: "identifier";
}

export interface IntegerLiteralNode extends AbstractVb_dotnetNode {
  type: "integer_literal";
}

export interface ModifierNode extends AbstractVb_dotnetNode {
  type: "modifier";
}

export interface PreprocessorDirectiveNode extends AbstractVb_dotnetNode {
  type: "preprocessor_directive";
}

export interface PrimitiveTypeNode extends AbstractVb_dotnetNode {
  type: "primitive_type";
}

export interface RelationalOperatorNode extends AbstractVb_dotnetNode {
  type: "relational_operator";
}

export type Vb_dotnetNode =
  | AddHandlerBlockNode
  | ArgumentNode
  | ArgumentListNode
  | ArrayLiteralNode
  | ArrayRankSpecifierNode
  | ArrayTypeNode
  | AsClauseNode
  | AssignmentStatementNode
  | AttributeNode
  | AttributeBlockNode
  | BinaryExpressionNode
  | BlankLineNode
  | CallStatementNode
  | CaseBlockNode
  | CaseClauseNode
  | CaseElseBlockNode
  | CatchBlockNode
  | ClassBlockNode
  | CompoundAssignmentStatementNode
  | ConstDeclarationNode
  | ConstructorDeclarationNode
  | ContinueStatementNode
  | DelegateDeclarationNode
  | DimStatementNode
  | DoStatementNode
  | ElementAccessNode
  | ElseClauseNode
  | ElseifClauseNode
  | EmptyStatementNode
  | EnumBlockNode
  | EnumMemberNode
  | EventDeclarationNode
  | ExitStatementNode
  | ExpressionNode
  | FieldDeclarationNode
  | FinallyBlockNode
  | ForEachStatementNode
  | ForStatementNode
  | GenericTypeNode
  | GetAccessorNode
  | GotoStatementNode
  | IfStatementNode
  | ImplementsClauseNode
  | ImportsStatementNode
  | InheritsClauseNode
  | InterfaceBlockNode
  | InterpolatedStringLiteralNode
  | InterpolationNode
  | InvocationNode
  | LabelStatementNode
  | LambdaExpressionNode
  | LambdaParameterNode
  | LeftHandSideNode
  | LiteralNode
  | MemberAccessNode
  | MemberInitializerNode
  | MethodDeclarationNode
  | ModifiersNode
  | ModuleBlockNode
  | NamespaceBlockNode
  | NamespaceNameNode
  | NewExpressionNode
  | ObjectInitializerNode
  | ObjectInitializersNode
  | OptionStatementsNode
  | ParameterNode
  | ParameterListNode
  | ParenthesizedExpressionNode
  | PropertyDeclarationNode
  | RaiseEventBlockNode
  | ReDimClauseNode
  | RedimStatementNode
  | RemoveHandlerBlockNode
  | ReturnStatementNode
  | SelectCaseStatementNode
  | SetAccessorNode
  | SourceFileNode
  | StatementNode
  | StringLiteralNode
  | StructureBlockNode
  | SyncLockStatementNode
  | TernaryExpressionNode
  | ThrowStatementNode
  | TryStatementNode
  | TypeNode
  | TypeArgumentListNode
  | TypeConstraintNode
  | TypeDeclarationNode
  | TypeParameterNode
  | TypeParametersNode
  | UnaryExpressionNode
  | UsingStatementNode
  | VariableDeclaratorNode
  | WhileStatementNode
  | WithInitializerNode
  | WithStatementNode
  | BooleanLiteralNode
  | CharacterLiteralNode
  | CommentNode
  | DateLiteralNode
  | FloatingPointLiteralNode
  | IdentifierNode
  | IntegerLiteralNode
  | ModifierNode
  | PreprocessorDirectiveNode
  | PrimitiveTypeNode
  | RelationalOperatorNode;
