/* Autogenerated, do not edit by hand. */
/* eslint-disable max-lines */

import type { SyntaxNode, Point } from "tree-sitter";

export interface AbstractKotlinNode extends SyntaxNode {
  parent: KotlinNode | null;
  namedChildren: Array<KotlinNode>;

  descendantsOfType(
    types: string | Array<string>,
    startPosition?: Point,
    endPosition?: Point,
  ): Array<KotlinNode>;
}

export interface AdditiveExpressionNode extends AbstractKotlinNode {
  type: "additive_expression";
}

export interface AnnotatedLambdaNode extends AbstractKotlinNode {
  type: "annotated_lambda";
}

export interface AnnotationNode extends AbstractKotlinNode {
  type: "annotation";
}

export interface AnonymousFunctionNode extends AbstractKotlinNode {
  type: "anonymous_function";
}

export interface AnonymousInitializerNode extends AbstractKotlinNode {
  type: "anonymous_initializer";
}

export interface AsExpressionNode extends AbstractKotlinNode {
  type: "as_expression";
}

export interface AssignmentNode extends AbstractKotlinNode {
  type: "assignment";
}

export interface BindingPatternKindNode extends AbstractKotlinNode {
  type: "binding_pattern_kind";
}

export interface BooleanLiteralNode extends AbstractKotlinNode {
  type: "boolean_literal";
}

export interface CallExpressionNode extends AbstractKotlinNode {
  type: "call_expression";
}

export interface CallSuffixNode extends AbstractKotlinNode {
  type: "call_suffix";
}

export interface CallableReferenceNode extends AbstractKotlinNode {
  type: "callable_reference";
}

export interface CatchBlockNode extends AbstractKotlinNode {
  type: "catch_block";
}

export interface CharacterEscapeSeqNode extends AbstractKotlinNode {
  type: "character_escape_seq";
}

export interface CharacterLiteralNode extends AbstractKotlinNode {
  type: "character_literal";
}

export interface CheckExpressionNode extends AbstractKotlinNode {
  type: "check_expression";
}

export interface ClassBodyNode extends AbstractKotlinNode {
  type: "class_body";
}

export interface ClassDeclarationNode extends AbstractKotlinNode {
  type: "class_declaration";
}

export interface ClassModifierNode extends AbstractKotlinNode {
  type: "class_modifier";
}

export interface ClassParameterNode extends AbstractKotlinNode {
  type: "class_parameter";
}

export interface CollectionLiteralNode extends AbstractKotlinNode {
  type: "collection_literal";
}

export interface CompanionObjectNode extends AbstractKotlinNode {
  type: "companion_object";
}

export interface ComparisonExpressionNode extends AbstractKotlinNode {
  type: "comparison_expression";
}

export interface ConjunctionExpressionNode extends AbstractKotlinNode {
  type: "conjunction_expression";
}

export interface ConstructorDelegationCallNode extends AbstractKotlinNode {
  type: "constructor_delegation_call";
}

export interface ConstructorInvocationNode extends AbstractKotlinNode {
  type: "constructor_invocation";
}

export interface ControlStructureBodyNode extends AbstractKotlinNode {
  type: "control_structure_body";
}

export interface DelegationSpecifierNode extends AbstractKotlinNode {
  type: "delegation_specifier";
}

export interface DestructuringDeclarationNode extends AbstractKotlinNode {
  type: "destructuring_declaration";
}

export interface DirectlyAssignableExpressionNode extends AbstractKotlinNode {
  type: "directly_assignable_expression";
}

export interface DisjunctionExpressionNode extends AbstractKotlinNode {
  type: "disjunction_expression";
}

export interface DoWhileStatementNode extends AbstractKotlinNode {
  type: "do_while_statement";
}

export interface ElvisExpressionNode extends AbstractKotlinNode {
  type: "elvis_expression";
}

export interface EnumClassBodyNode extends AbstractKotlinNode {
  type: "enum_class_body";
}

export interface EnumEntryNode extends AbstractKotlinNode {
  type: "enum_entry";
}

export interface EqualityExpressionNode extends AbstractKotlinNode {
  type: "equality_expression";
}

export interface ExplicitDelegationNode extends AbstractKotlinNode {
  type: "explicit_delegation";
}

export interface FileAnnotationNode extends AbstractKotlinNode {
  type: "file_annotation";
}

export interface FinallyBlockNode extends AbstractKotlinNode {
  type: "finally_block";
}

export interface ForStatementNode extends AbstractKotlinNode {
  type: "for_statement";
}

export interface FunctionBodyNode extends AbstractKotlinNode {
  type: "function_body";
}

export interface FunctionDeclarationNode extends AbstractKotlinNode {
  type: "function_declaration";

  receiverNode: ReceiverTypeNode | null;
}

export interface FunctionModifierNode extends AbstractKotlinNode {
  type: "function_modifier";
}

export interface FunctionTypeNode extends AbstractKotlinNode {
  type: "function_type";

  receiverNode: ReceiverTypeNode | null;
}

export interface FunctionTypeParametersNode extends AbstractKotlinNode {
  type: "function_type_parameters";
}

export interface FunctionValueParametersNode extends AbstractKotlinNode {
  type: "function_value_parameters";
}

export interface GetterNode extends AbstractKotlinNode {
  type: "getter";
}

export interface GuardConditionNode extends AbstractKotlinNode {
  type: "guard_condition";
}

export interface IdentifierNode extends AbstractKotlinNode {
  type: "identifier";
}

export interface IfExpressionNode extends AbstractKotlinNode {
  type: "if_expression";

  alternativeNode: ControlStructureBodyNode | null;
  conditionNode:
    | AdditiveExpressionNode
    | AnonymousFunctionNode
    | AsExpressionNode
    | BinLiteralNode
    | BooleanLiteralNode
    | CallExpressionNode
    | CallableReferenceNode
    | CharacterLiteralNode
    | CheckExpressionNode
    | CollectionLiteralNode
    | ComparisonExpressionNode
    | ConjunctionExpressionNode
    | DisjunctionExpressionNode
    | ElvisExpressionNode
    | EqualityExpressionNode
    | HexLiteralNode
    | IfExpressionNode
    | IndexingExpressionNode
    | InfixExpressionNode
    | IntegerLiteralNode
    | JumpExpressionNode
    | LambdaLiteralNode
    | LongLiteralNode
    | MultiplicativeExpressionNode
    | NavigationExpressionNode
    | NullLiteralNode
    | ObjectLiteralNode
    | ParenthesizedExpressionNode
    | PostfixExpressionNode
    | PrefixExpressionNode
    | RangeExpressionNode
    | RealLiteralNode
    | SimpleIdentifierNode
    | SpreadExpressionNode
    | StringLiteralNode
    | SuperExpressionNode
    | ThisExpressionNode
    | TryExpressionNode
    | UnsignedLiteralNode
    | WhenExpressionNode;
  consequenceNode: ControlStructureBodyNode | null;
}

export interface ImportAliasNode extends AbstractKotlinNode {
  type: "import_alias";
}

export interface ImportHeaderNode extends AbstractKotlinNode {
  type: "import_header";
}

export interface ImportListNode extends AbstractKotlinNode {
  type: "import_list";
}

export interface IndexingExpressionNode extends AbstractKotlinNode {
  type: "indexing_expression";
}

export interface IndexingSuffixNode extends AbstractKotlinNode {
  type: "indexing_suffix";
}

export interface InfixExpressionNode extends AbstractKotlinNode {
  type: "infix_expression";
}

export interface InheritanceModifierNode extends AbstractKotlinNode {
  type: "inheritance_modifier";
}

export interface InterpolatedExpressionNode extends AbstractKotlinNode {
  type: "interpolated_expression";
}

export interface InterpolatedIdentifierNode extends AbstractKotlinNode {
  type: "interpolated_identifier";
}

export interface JumpExpressionNode extends AbstractKotlinNode {
  type: "jump_expression";
}

export interface LabelNode extends AbstractKotlinNode {
  type: "label";
}

export interface LambdaLiteralNode extends AbstractKotlinNode {
  type: "lambda_literal";
}

export interface LambdaParametersNode extends AbstractKotlinNode {
  type: "lambda_parameters";
}

export interface LongLiteralNode extends AbstractKotlinNode {
  type: "long_literal";
}

export interface MemberModifierNode extends AbstractKotlinNode {
  type: "member_modifier";
}

export interface ModifiersNode extends AbstractKotlinNode {
  type: "modifiers";
}

export interface MultiVariableDeclarationNode extends AbstractKotlinNode {
  type: "multi_variable_declaration";
}

export interface MultiplicativeExpressionNode extends AbstractKotlinNode {
  type: "multiplicative_expression";
}

export interface NavigationExpressionNode extends AbstractKotlinNode {
  type: "navigation_expression";
}

export interface NavigationSuffixNode extends AbstractKotlinNode {
  type: "navigation_suffix";
}

export interface NotNullableTypeNode extends AbstractKotlinNode {
  type: "not_nullable_type";
}

export interface NullableTypeNode extends AbstractKotlinNode {
  type: "nullable_type";
}

export interface ObjectDeclarationNode extends AbstractKotlinNode {
  type: "object_declaration";
}

export interface ObjectLiteralNode extends AbstractKotlinNode {
  type: "object_literal";
}

export interface PackageHeaderNode extends AbstractKotlinNode {
  type: "package_header";
}

export interface ParameterNode extends AbstractKotlinNode {
  type: "parameter";
}

export interface ParameterModifierNode extends AbstractKotlinNode {
  type: "parameter_modifier";
}

export interface ParameterModifiersNode extends AbstractKotlinNode {
  type: "parameter_modifiers";
}

export interface ParameterWithOptionalTypeNode extends AbstractKotlinNode {
  type: "parameter_with_optional_type";
}

export interface ParenthesizedExpressionNode extends AbstractKotlinNode {
  type: "parenthesized_expression";
}

export interface ParenthesizedTypeNode extends AbstractKotlinNode {
  type: "parenthesized_type";
}

export interface ParenthesizedUserTypeNode extends AbstractKotlinNode {
  type: "parenthesized_user_type";
}

export interface PlatformModifierNode extends AbstractKotlinNode {
  type: "platform_modifier";
}

export interface PostfixExpressionNode extends AbstractKotlinNode {
  type: "postfix_expression";
}

export interface PrefixExpressionNode extends AbstractKotlinNode {
  type: "prefix_expression";
}

export interface PrimaryConstructorNode extends AbstractKotlinNode {
  type: "primary_constructor";
}

export interface PropertyDeclarationNode extends AbstractKotlinNode {
  type: "property_declaration";

  receiverNode: ReceiverTypeNode | null;
}

export interface PropertyDelegateNode extends AbstractKotlinNode {
  type: "property_delegate";
}

export interface PropertyModifierNode extends AbstractKotlinNode {
  type: "property_modifier";
}

export interface RangeExpressionNode extends AbstractKotlinNode {
  type: "range_expression";
}

export interface RangeTestNode extends AbstractKotlinNode {
  type: "range_test";
}

export interface ReceiverTypeNode extends AbstractKotlinNode {
  type: "receiver_type";
}

export interface ReificationModifierNode extends AbstractKotlinNode {
  type: "reification_modifier";
}

export interface SecondaryConstructorNode extends AbstractKotlinNode {
  type: "secondary_constructor";
}

export interface SetterNode extends AbstractKotlinNode {
  type: "setter";
}

export interface ShebangLineNode extends AbstractKotlinNode {
  type: "shebang_line";
}

export interface SimpleIdentifierNode extends AbstractKotlinNode {
  type: "simple_identifier";
}

export interface SourceFileNode extends AbstractKotlinNode {
  type: "source_file";
}

export interface SpreadExpressionNode extends AbstractKotlinNode {
  type: "spread_expression";
}

export interface StatementsNode extends AbstractKotlinNode {
  type: "statements";
}

export interface StringLiteralNode extends AbstractKotlinNode {
  type: "string_literal";
}

export interface SuperExpressionNode extends AbstractKotlinNode {
  type: "super_expression";
}

export interface ThisExpressionNode extends AbstractKotlinNode {
  type: "this_expression";
}

export interface TryExpressionNode extends AbstractKotlinNode {
  type: "try_expression";
}

export interface TypeAliasNode extends AbstractKotlinNode {
  type: "type_alias";
}

export interface TypeArgumentsNode extends AbstractKotlinNode {
  type: "type_arguments";
}

export interface TypeConstraintNode extends AbstractKotlinNode {
  type: "type_constraint";
}

export interface TypeConstraintsNode extends AbstractKotlinNode {
  type: "type_constraints";
}

export interface TypeIdentifierNode extends AbstractKotlinNode {
  type: "type_identifier";
}

export interface TypeModifiersNode extends AbstractKotlinNode {
  type: "type_modifiers";
}

export interface TypeParameterNode extends AbstractKotlinNode {
  type: "type_parameter";
}

export interface TypeParameterModifiersNode extends AbstractKotlinNode {
  type: "type_parameter_modifiers";
}

export interface TypeParametersNode extends AbstractKotlinNode {
  type: "type_parameters";
}

export interface TypeProjectionNode extends AbstractKotlinNode {
  type: "type_projection";
}

export interface TypeProjectionModifiersNode extends AbstractKotlinNode {
  type: "type_projection_modifiers";
}

export interface TypeTestNode extends AbstractKotlinNode {
  type: "type_test";
}

export interface UnsignedLiteralNode extends AbstractKotlinNode {
  type: "unsigned_literal";
}

export interface UseSiteTargetNode extends AbstractKotlinNode {
  type: "use_site_target";
}

export interface UserTypeNode extends AbstractKotlinNode {
  type: "user_type";
}

export interface ValueArgumentNode extends AbstractKotlinNode {
  type: "value_argument";
}

export interface ValueArgumentsNode extends AbstractKotlinNode {
  type: "value_arguments";
}

export interface VariableDeclarationNode extends AbstractKotlinNode {
  type: "variable_declaration";
}

export interface VarianceModifierNode extends AbstractKotlinNode {
  type: "variance_modifier";
}

export interface VisibilityModifierNode extends AbstractKotlinNode {
  type: "visibility_modifier";
}

export interface WhenConditionNode extends AbstractKotlinNode {
  type: "when_condition";
}

export interface WhenEntryNode extends AbstractKotlinNode {
  type: "when_entry";
}

export interface WhenExpressionNode extends AbstractKotlinNode {
  type: "when_expression";
}

export interface WhenSubjectNode extends AbstractKotlinNode {
  type: "when_subject";
}

export interface WhileStatementNode extends AbstractKotlinNode {
  type: "while_statement";
}

export interface BinLiteralNode extends AbstractKotlinNode {
  type: "bin_literal";
}

export interface HexLiteralNode extends AbstractKotlinNode {
  type: "hex_literal";
}

export interface IntegerLiteralNode extends AbstractKotlinNode {
  type: "integer_literal";
}

export interface InterpolationExpressionEndNode extends AbstractKotlinNode {
  type: "interpolation_expression_end";
}

export interface InterpolationExpressionStartNode extends AbstractKotlinNode {
  type: "interpolation_expression_start";
}

export interface InterpolationIdentifierStartNode extends AbstractKotlinNode {
  type: "interpolation_identifier_start";
}

export interface LineCommentNode extends AbstractKotlinNode {
  type: "line_comment";
}

export interface MultilineCommentNode extends AbstractKotlinNode {
  type: "multiline_comment";
}

export interface NullLiteralNode extends AbstractKotlinNode {
  type: "null_literal";
}

export interface QuestNode extends AbstractKotlinNode {
  type: "quest";
}

export interface RealLiteralNode extends AbstractKotlinNode {
  type: "real_literal";
}

export interface StringContentNode extends AbstractKotlinNode {
  type: "string_content";
}

export interface WildcardImportNode extends AbstractKotlinNode {
  type: "wildcard_import";
}

export type KotlinNode =
  | AdditiveExpressionNode
  | AnnotatedLambdaNode
  | AnnotationNode
  | AnonymousFunctionNode
  | AnonymousInitializerNode
  | AsExpressionNode
  | AssignmentNode
  | BindingPatternKindNode
  | BooleanLiteralNode
  | CallExpressionNode
  | CallSuffixNode
  | CallableReferenceNode
  | CatchBlockNode
  | CharacterEscapeSeqNode
  | CharacterLiteralNode
  | CheckExpressionNode
  | ClassBodyNode
  | ClassDeclarationNode
  | ClassModifierNode
  | ClassParameterNode
  | CollectionLiteralNode
  | CompanionObjectNode
  | ComparisonExpressionNode
  | ConjunctionExpressionNode
  | ConstructorDelegationCallNode
  | ConstructorInvocationNode
  | ControlStructureBodyNode
  | DelegationSpecifierNode
  | DestructuringDeclarationNode
  | DirectlyAssignableExpressionNode
  | DisjunctionExpressionNode
  | DoWhileStatementNode
  | ElvisExpressionNode
  | EnumClassBodyNode
  | EnumEntryNode
  | EqualityExpressionNode
  | ExplicitDelegationNode
  | FileAnnotationNode
  | FinallyBlockNode
  | ForStatementNode
  | FunctionBodyNode
  | FunctionDeclarationNode
  | FunctionModifierNode
  | FunctionTypeNode
  | FunctionTypeParametersNode
  | FunctionValueParametersNode
  | GetterNode
  | GuardConditionNode
  | IdentifierNode
  | IfExpressionNode
  | ImportAliasNode
  | ImportHeaderNode
  | ImportListNode
  | IndexingExpressionNode
  | IndexingSuffixNode
  | InfixExpressionNode
  | InheritanceModifierNode
  | InterpolatedExpressionNode
  | InterpolatedIdentifierNode
  | JumpExpressionNode
  | LabelNode
  | LambdaLiteralNode
  | LambdaParametersNode
  | LongLiteralNode
  | MemberModifierNode
  | ModifiersNode
  | MultiVariableDeclarationNode
  | MultiplicativeExpressionNode
  | NavigationExpressionNode
  | NavigationSuffixNode
  | NotNullableTypeNode
  | NullableTypeNode
  | ObjectDeclarationNode
  | ObjectLiteralNode
  | PackageHeaderNode
  | ParameterNode
  | ParameterModifierNode
  | ParameterModifiersNode
  | ParameterWithOptionalTypeNode
  | ParenthesizedExpressionNode
  | ParenthesizedTypeNode
  | ParenthesizedUserTypeNode
  | PlatformModifierNode
  | PostfixExpressionNode
  | PrefixExpressionNode
  | PrimaryConstructorNode
  | PropertyDeclarationNode
  | PropertyDelegateNode
  | PropertyModifierNode
  | RangeExpressionNode
  | RangeTestNode
  | ReceiverTypeNode
  | ReificationModifierNode
  | SecondaryConstructorNode
  | SetterNode
  | ShebangLineNode
  | SimpleIdentifierNode
  | SourceFileNode
  | SpreadExpressionNode
  | StatementsNode
  | StringLiteralNode
  | SuperExpressionNode
  | ThisExpressionNode
  | TryExpressionNode
  | TypeAliasNode
  | TypeArgumentsNode
  | TypeConstraintNode
  | TypeConstraintsNode
  | TypeIdentifierNode
  | TypeModifiersNode
  | TypeParameterNode
  | TypeParameterModifiersNode
  | TypeParametersNode
  | TypeProjectionNode
  | TypeProjectionModifiersNode
  | TypeTestNode
  | UnsignedLiteralNode
  | UseSiteTargetNode
  | UserTypeNode
  | ValueArgumentNode
  | ValueArgumentsNode
  | VariableDeclarationNode
  | VarianceModifierNode
  | VisibilityModifierNode
  | WhenConditionNode
  | WhenEntryNode
  | WhenExpressionNode
  | WhenSubjectNode
  | WhileStatementNode
  | BinLiteralNode
  | HexLiteralNode
  | IntegerLiteralNode
  | InterpolationExpressionEndNode
  | InterpolationExpressionStartNode
  | InterpolationIdentifierStartNode
  | LineCommentNode
  | MultilineCommentNode
  | NullLiteralNode
  | QuestNode
  | RealLiteralNode
  | StringContentNode
  | WildcardImportNode;
